### ISSUE TITLE
db question

### ISSUE THREAD

**Issue by vitaly-t** [davschne/friending-library2#14]
May I ask you, why you decided not to use pg-promise? I wonder whether there were features missed not present in the library.

Thank you!

**Comment by davschne** [comment]
Hi, thanks for your question! I'm not 100% settled on my choice of library to interface with Postgres. I like pg-promise, but at the moment I've switched to Massive mainly because it allows me to import .sql files. I was trying to figure out how to do that with pg-promise, but it seemed like I would have had to parse the .sql files myself.

**Comment by vitaly-t** [comment]
This would be trivial:

``` js
var fs = require("fs");
var EOL = require("fs").EOL;

fs.readFile("queries.sql", (err, f)=> {
    var queries = f.toString().split(EOL).filter(f=> {
        return f.trim().length > 0; // get only non-empty lines;
    });
    db.tx(t=>t.batch(queries.map(q=>t.query(q))))
        .catch(error=> {

        });
});
```

**Comment by davschne** [comment]
Thanks very much for the suggestion! Am I correct in thinking, though, that would only work if queries don't overflow to multiple lines? I've been writing my SQL in this style:

```
SELECT * FROM table1
WHERE col1 IN (
    SELECT col2 FROM table2
);
```

If I'm splitting on EOL, I guess I'd then have to join array elements that don't terminate with a semi-colon to the following elements?

**Comment by vitaly-t** [comment]
Yes, the special formatting in `queries.sql` would have to be looked at, if needed. But once you have the array of queries, it is as simple with `pg-promise` as one line that I showed you ;)

There are probably some libraries to even do that automatically, to read an SQL file and provide an array of queries.

**Comment by davschne** [comment]
Totally. Yeah, I thought there must be a library to parse sql into queries, but I've been mainly finding libraries that parse it into abstract syntax trees.

**Comment by vitaly-t** [comment]
I've just looked at your SQL files. I thought they contained multiple queries, but they all contain just one multi-line query. Handling such is very easy. All you have to do is replace each `\r\n` with a space, and you're good to go executing it through pg-promise.

**Comment by vitaly-t** [comment]
Actually, ignore my previous post, you don't need to process them at all, they can execute through pg-promise directly! :) So much for whatever you think Massive does to those files - nothing, it turns out :)

To execute one query from file:

``` js
fs.readFile("myQuery.sql", "utf-8", (err, q)=> {
    if (err) {
        console.log("Error:", err);
    } else {
        db.query(q)
            .catch(e=> {
                console.log("Error:", e);
            });
    }
});
```

**Comment by vitaly-t** [comment]
@davschne I've just released pg-promise [2.9.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.2.9.0). Check out the new feature - [Query Files](https://github.com/vitaly-t/pg-promise#query-files). I believe this is the one that can make all the difference ;)

**Comment by davschne** [comment]
That's great, Vitaly! Will definitely check it out.

**Comment by vitaly-t** [comment]
Also, consider this: [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo). I believe it contains many answers to this subject.

**Comment by davschne** [comment]
Cool, that's very interesting. Quick question for you: can I create prepared statements using pg-promise like in pg (https://github.com/brianc/node-postgres/wiki/Prepared-Statements)? Example:

```
client.query( {
      text :  "INSERT INTO my_table(field1,field2) VALUES ($1, $2)", 
      name : "insert-my-data"
});
```

**Comment by davschne** [comment]
Disregard my question; I just found the answer in your documentation.

**Comment by vitaly-t** [comment]
Yep, it's always been supported :) https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#prepared-statements

**Comment by vitaly-t** [comment]
A useful read in spare time - [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost) ;)

**Comment by davschne** [comment]
Thanks; will check it out.
